name: Blazor Web Assembly 2

on:
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write
  
jobs:
  deploy-to-github-pages:
    runs-on: ubuntu-latest

    steps:
    # Checkout
    - uses: actions/checkout@v3

    # Publicar el proyecto Blazor WASM en la carpeta 'release'
    - name: Publish Blazor WASM Project
      run: dotnet publish BlazorApp.csproj -c Release -o release --nologo
  
    - name: Rewrite base href
      uses: SteveSandersonMS/ghaction-rewrite-base-href@5b54862a8831e012d4f1a8b2660894415fdde8ec # v1.1.0
      with:
        html_path: release/wwwroot/index.html
        base_href: /BlazorApp/

    # Copiar index.html a 404.html para manejar errores 404
    - name: Copy index.html to 404.html
      run: cp release/wwwroot/index.html release/wwwroot/404.html

    # Añadir el archivo .nojekyll para evitar que GitHub Pages lo procese como Jekyll
    - name: Add .nojekyll file
      run: touch release/wwwroot/.nojekyll

    # Configura GitHub Pages
    - name: Setup Pages
      uses: actions/configure-pages@v5
    
    # Sube los archivos generados como artifact
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v4
      with:
        path: release/wwwroot
    
    # Despliega a GitHub Pages
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
